### ISSUE TITLE
Could not infer dtype of collections.OrderedDict

### ISSUE THREAD

**Issue by Arkitect-z** [pblatter/ettrack#8]
**error message**
```
(et) wsl@Red7000p:~/program/ettrack$ /home/wsl/miniconda3/envs/et/bin/python /home/wsl/program/ettrack/pytracking/run_video.py et_tracker et_tracker /home/wsl/program/ettrack/Roadtraffic.mp4
checkpoint epoch provided: 35
checkpoint path:  ./checkpoints/et_tracker/checkpoint_e35.pth
loading model from:  ./checkpoints/et_tracker/checkpoint_e35.pth
loading the checkpoint strict: True
model initializing successful
QObject::moveToThread: Current thread (0x73f2b20) is not the object's thread (0x7546b40).
Cannot move to target thread (0x73f2b20)
Select a ROI and then press SPACE or ENTER button!
Cancel the selection process by pressing c button!
tracker weight style: regular
Traceback (most recent call last):
  File "/home/wsl/program/ettrack/pytracking/run_video.py", line 38, in <module>
    main()
  File "/home/wsl/program/ettrack/pytracking/run_video.py", line 34, in main
    run_video(args.tracker_name, args.tracker_param,args.videofile, args.optional_box, args.debug, args.save_results)
  File "/home/wsl/program/ettrack/pytracking/run_video.py", line 20, in run_video
    tracker.run_video(videofilepath=videofile, optional_box=optional_box, debug=debug, save_results=save_results)
  File "/home/wsl/program/ettrack/pytracking/../pytracking/evaluation/tracker.py", line 298, in run_video
    tracker.initialize(frame, _build_init_info(init_state))
  File "/home/wsl/program/ettrack/pytracking/../pytracking/tracker/et_tracker/et_tracker.py", line 51, in initialize
    state = torch.tensor(info['init_bbox']) # x,y,w,h
RuntimeError: Could not infer dtype of collections.OrderedDict
```
**part of my conda environment**
```
# packages in environment at /home/wsl/miniconda3/envs/et:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main  
_openmp_mutex             5.1                       1_gnu  
cudatoolkit               10.1.243             h6bb024c_0  
ffmpeg                    4.3                  hf484d3e_0    pytorch
jpeg4py                   0.1.4                    pypi_0    pypi
libwebp                   1.2.0                h89dd481_0  
libxcb                    1.15                 h7f8727e_0  
libxml2                   2.9.14               h74e7548_0  
numpy                     1.24.3           py38hf6e8229_1  
numpy-base                1.24.3           py38h060ed82_1  
opencv-python             4.8.0.74                 pypi_0    pypi
pip                       23.1.2           py38h06a4308_0  
pycparser                 2.21                     pypi_0    pypi
pyparsing                 3.0.9            py38h06a4308_0  
pyqt                      5.9.2            py38h05f1152_4  
python                    3.8.17               h7a1cb2a_0  
python-dateutil           2.8.2              pyhd3eb1b0_0  
pytorch                   1.8.1           py3.8_cuda10.1_cudnn7.6.3_0    pytorch
pyyaml                    6.0                      pypi_0    pypi
qt                        5.9.7                h5867ecd_1  
scipy                     1.10.1                   pypi_0    pypi
six                       1.16.0             pyhd3eb1b0_1  
```
**how I run the code**
Generate the relevant files:

python -c "from pytracking.evaluation.environment import create_default_local_file; create_default_local_file()"
python -c "from ltr.admin.environment import create_default_local_file; create_default_local_file()"

but I did not modify the local.py

and then I put the https://data.vision.ee.ethz.ch/kanakism/checkpoint_e35.pth to ./checkpoints/et_tracker/

**Comment by xyl-507** [comment]
@Arkitect-z 
Hello！
I also met this problem. Have you solved it？

**Comment by crankyz** [comment]
Same issue.

**Comment by basar-yilmaz** [comment]
It would be a good idea to change the 51th line of `pytracking/tracker/et_tracker/et_tracker.py` to:

`state = torch.tensor(info['init_bbox'][1]) # x,y,w,h`

If you still need after 1 year :)
